### ISSUE TITLE
要是能支持上传到微博就好了

### ISSUE THREAD

**Issue by goxofy** [int64ago/getlink#1]

**Comment by int64ago** [comment]
我始终对微博图床不放心，也不知道它何时会启用 Referer 检测

**Comment by goxofy** [comment]
目前还木有，我现在用的是自己写的cli版本的，用的是移动版微博的接口，要是getlink可以在后台指定使用七牛或者微博就好了。。。

**Comment by int64ago** [comment]
嗯，这个实现不难，我有空会加上，到时候 @ 你
PS：你是单独申请的小号？调用频率高了不会被封？

**Comment by goxofy** [comment]
是申请的小号，用了一年多了没出现问题

**Comment by goxofy** [comment]
谢谢！
