### ISSUE TITLE
Mobile 上URL Markdown HTML 链接不能正常显示

### ISSUE THREAD

**Issue by Xuchenhao** [int64ago/getlink#2]
![](http://moefq.com/images/2016/05/17/a6712f14466661ed0090624b7daa81dc.png)
很不错的项目呢

**Comment by int64ago** [comment]
不能正常显示是指什么呢？

**Comment by Xuchenhao** [comment]
在电脑上，点击URL, HTML, Markdown 均可复制代码
在Mobile上不行，能不能在Mobile上变成点击显示代码，让用户自己复制

**Comment by int64ago** [comment]
可能是不支持 Safari 吧 —_— ，Chrome 无压力
